/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import interfaces.reportes.ReporteVentas;
import interfaces.ventas.VentasGenerar;
import interfaces.inventario.InventarioDesHab;
import interfaces.inventario.Inventario;
import interfaces.inscripciones.InscripcionKick;
import interfaces.inscripciones.Inscripcion;
import interfaces.cobros.CobrarKick;
import interfaces.cobros.Cobrar;
import interfaces.altasbajas.altas.KickBoxingAltas;
import interfaces.altasbajas.altas.SemanalesAltas;
import interfaces.altasbajas.altas.MensualesAltas;
import interfaces.altasbajas.bajas.MensualesBajas;
import interfaces.altasbajas.bajas.SemanalesBajas;
import interfaces.altasbajas.bajas.KickBoxingBajas;
import interfaces.reportes.*;
import com.jtattoo.plaf.acryl.AcrylLookAndFeel;
import com.jtattoo.plaf.aero.AeroLookAndFeel;
import com.jtattoo.plaf.aluminium.AluminiumLookAndFeel;
import com.jtattoo.plaf.bernstein.BernsteinLookAndFeel;
import com.jtattoo.plaf.fast.FastLookAndFeel;
import com.jtattoo.plaf.graphite.GraphiteLookAndFeel;
import com.jtattoo.plaf.luna.LunaLookAndFeel;
import com.jtattoo.plaf.mcwin.McWinLookAndFeel;
import com.jtattoo.plaf.mint.MintLookAndFeel;
import com.jtattoo.plaf.noire.NoireLookAndFeel;
import com.jtattoo.plaf.smart.SmartLookAndFeel;
import com.jtattoo.plaf.texture.TextureLookAndFeel;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.plaf.basic.BasicLookAndFeel;
import javax.swing.plaf.metal.MetalLookAndFeel;
import javax.swing.plaf.multi.MultiLookAndFeel;

/**
 *
 * @author jesus
 */
public class Principal extends javax.swing.JFrame implements Runnable{
    String hora, minutos, segundos, ampm, fechaFormateada;
    SimpleDateFormat formato;
    Calendar calendario;
    Date fechaActual;
    Thread t1;
    Inscripcion inscripcionForm;
    Cobrar cobrarMensualidad;
    Inventario inventario;
    VentasGenerar ventasGenerar;
    InventarioDesHab inventarioDesHab;
    ReporteVentas reporteVentas;
    InscripcionKick inscripcionKick;
    CobrarKick cobrarKick;
    MensualesAltas mensualesAltas;
    SemanalesAltas semanalesAltas;
    KickBoxingAltas kickBoxingAltas;
    MensualesBajas mensualesBajas;
    SemanalesBajas semanalesBajas;
    KickBoxingBajas kickBoxingBajas;
    ReportePagos reportePagos;
    ReporteMensualidades reporteMensualidades;
    ReportePagosSemanales reportePagosSemanales;
    ReporteVisitas reporteVisitas;
    ReportePagosKick reportePagosKick;
    ReporteInventario reporteInventario;
    ReporteAlumnosKick reporteAlumnosKick;
    /**
     * Creates new form Principal
     */
    public Principal() {
        formato = new SimpleDateFormat("dd/MM/yyyy");
        initComponents();
        t1 = new Thread(this);
        t1.start();
        setLocationRelativeTo(null);
        setTitle("Gym");
        setVisible(true);
        setResizable(false);
        labelBienvenida.setVisible(false);
        btnReintentarConexion.setVisible(false);
        desHabMenus(false);
        hiloConexion();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    private void desHabMenus(boolean desHab){
        btnMenuInscripcion.setEnabled(desHab);
        btnMenuCobros.setEnabled(desHab);
        btnMenuInventario.setEnabled(desHab);
        btnMenuVenta.setEnabled(desHab);
        btnMenuAltasBajas.setEnabled(desHab);
        btnMenuReportes.setEnabled(desHab);
    }
    
    private void hiloConexion(){
        new Thread(){
            @Override
            public void run(){
                comprobarConexion();
            }
        }.start();
    }
    
    private void comprobarConexion(){
        labelEstadoConexion.setText("Realizando conexión a la base de datos, por favor espere...");
        labelCargando.setVisible(true);
        if(gym.MySQLConnection.conectarBD()){
            labelEstadoConexion.setText("Conexión éxitosa a la base de datos");
            labelCargando.setVisible(false);
            labelBienvenida.setVisible(true);
            btnReintentarConexion.setVisible(false);
            desHabMenus(true);
        } else{
            labelBienvenida.setVisible(false);
            labelCargando.setVisible(false);
            labelEstadoConexion.setText("Fallo en la conexión");
            btnReintentarConexion.setVisible(true);
            desHabMenus(false);
        }
    }
    
    private void calcula(){
        fechaActual = new Date();
        calendario = new GregorianCalendar();
        calendario.setTime(fechaActual);
        //Operador ternario
        ampm = calendario.get(Calendar.AM_PM) == Calendar.AM ? "AM" : "PM";
        fechaFormateada = formato.format(fechaActual);
        if(ampm.equals("PM")){
            int h = calendario.get(Calendar.HOUR_OF_DAY) - 12;
            //Para agregar el cero a la izquierda si es que es la hora de una cifra
            //Ej. 09:00:00 AM
            hora = h > 9 ? "" + h : "0" + h;
        } else {
            hora = calendario.get(Calendar.HOUR_OF_DAY)  > 9 ? "" + 
                    calendario.get(Calendar.HOUR_OF_DAY) : "0" + 
                    calendario.get(Calendar.HOUR_OF_DAY);
        }
        minutos = calendario.get(Calendar.MINUTE) > 9 ? "" + 
                calendario.get(Calendar.MINUTE) : "0" + 
                calendario.get(Calendar.MINUTE);
        
        segundos = calendario.get(Calendar.SECOND) > 9 ? "" + 
                calendario.get(Calendar.SECOND) : "0" + 
                calendario.get(Calendar.SECOND);
    }
    
    @Override
    public void run(){
        Thread ct = Thread.currentThread();
        while(ct == t1){
            calcula();
            labelFechaHora.setText(fechaFormateada + " | " + hora + ":" + 
                    minutos + ":" + segundos + " " + ampm);
            try{
                Thread.sleep(1000);
            } catch(InterruptedException e){
                
            }
        }
    }
    
    public void centrarVentanaInterna(JInternalFrame internalFrame){
        int x = (desktopPane.getWidth() / 2) - internalFrame.getWidth() / 2;
        int y = (desktopPane.getWidth() / 2) - internalFrame.getWidth() / 2;
        
        if(internalFrame.isShowing()){
            internalFrame.setLocation(x, y);
        } else {
            desktopPane.add(internalFrame);
            internalFrame.setLocation(x, y);
            internalFrame.show();
        }
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelFechaHora = new javax.swing.JLabel();
        desktopPane = new javax.swing.JDesktopPane();
        labelEstadoConexion = new javax.swing.JLabel();
        labelCargando = new javax.swing.JLabel();
        labelBienvenida = new javax.swing.JLabel();
        btnReintentarConexion = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        btnMenuInscripcion = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        btnMenuCobros = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        btnMenuInventario = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        btnMenuVenta = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        btnMenuAltasBajas = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        btnMenuReportes = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenuItem23 = new javax.swing.JMenuItem();
        jMenuItem24 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelFechaHora.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        desktopPane.setPreferredSize(new java.awt.Dimension(920, 380));

        labelEstadoConexion.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        labelEstadoConexion.setText("Realizando conexión a la base de datos, por favor espere...");

        labelCargando.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cargando.gif"))); // NOI18N

        labelBienvenida.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        labelBienvenida.setText("Seleccione una opción del menú de la parte superior de la pantalla");

        btnReintentarConexion.setText("Reintentar conexión");
        btnReintentarConexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReintentarConexionActionPerformed(evt);
            }
        });

        desktopPane.setLayer(labelEstadoConexion, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(labelCargando, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(labelBienvenida, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(btnReintentarConexion, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopPaneLayout.createSequentialGroup()
                .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(desktopPaneLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(labelEstadoConexion)
                        .addGap(33, 33, 33)
                        .addComponent(labelCargando))
                    .addGroup(desktopPaneLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(labelBienvenida))
                    .addGroup(desktopPaneLayout.createSequentialGroup()
                        .addGap(327, 327, 327)
                        .addComponent(btnReintentarConexion, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopPaneLayout.createSequentialGroup()
                .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(desktopPaneLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(labelEstadoConexion, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(desktopPaneLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(labelCargando)))
                .addGap(54, 54, 54)
                .addComponent(labelBienvenida)
                .addGap(46, 46, 46)
                .addComponent(btnReintentarConexion, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        btnMenuInscripcion.setText("Inscripción");

        jMenuItem8.setText("Clientes");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        btnMenuInscripcion.add(jMenuItem8);

        jMenuItem6.setText("KickBoxing");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        btnMenuInscripcion.add(jMenuItem6);

        jMenuBar1.add(btnMenuInscripcion);

        btnMenuCobros.setText("Cobros");

        jMenuItem1.setText("Clientes");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        btnMenuCobros.add(jMenuItem1);

        jMenuItem7.setText("KickBoxing");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        btnMenuCobros.add(jMenuItem7);

        jMenuBar1.add(btnMenuCobros);

        btnMenuInventario.setText("Inventario");

        jMenuItem9.setText("Inventario");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        btnMenuInventario.add(jMenuItem9);

        jMenuItem2.setText("Inhabilitados");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        btnMenuInventario.add(jMenuItem2);

        jMenuBar1.add(btnMenuInventario);

        btnMenuVenta.setText("Venta");

        jMenuItem4.setText("Generar");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        btnMenuVenta.add(jMenuItem4);

        jMenuBar1.add(btnMenuVenta);

        btnMenuAltasBajas.setText("Altas/Bajas");

        jMenu2.setText("Altas");

        jMenuItem10.setText("Mensuales");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem10);

        jMenuItem11.setText("Semanales");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem11);

        jMenuItem12.setText("KickBoxing");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem12);

        btnMenuAltasBajas.add(jMenu2);

        jMenu3.setText("Bajas");

        jMenuItem13.setText("Mensuales");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem13);

        jMenuItem14.setText("Semanales");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem14);

        jMenuItem15.setText("KickBoxing");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem15);

        btnMenuAltasBajas.add(jMenu3);

        jMenuBar1.add(btnMenuAltasBajas);

        btnMenuReportes.setText("Reportes");

        jMenuItem5.setText("Ventas");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        btnMenuReportes.add(jMenuItem5);

        jMenuItem3.setText("Pagos");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        btnMenuReportes.add(jMenuItem3);

        jMenuItem16.setText("Mensualidades");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        btnMenuReportes.add(jMenuItem16);

        jMenuItem17.setText("Pagos semanales");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        btnMenuReportes.add(jMenuItem17);

        jMenuItem18.setText("Visitas");
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        btnMenuReportes.add(jMenuItem18);

        jMenuItem19.setText("Pagos Kick Boxing");
        jMenuItem19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem19ActionPerformed(evt);
            }
        });
        btnMenuReportes.add(jMenuItem19);

        jMenuItem20.setText("Inventario");
        jMenuItem20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem20ActionPerformed(evt);
            }
        });
        btnMenuReportes.add(jMenuItem20);

        jMenuItem21.setText("Alumnos Kick Boxing");
        jMenuItem21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem21ActionPerformed(evt);
            }
        });
        btnMenuReportes.add(jMenuItem21);

        jMenuItem22.setText("Inscripciones");
        btnMenuReportes.add(jMenuItem22);

        jMenuItem23.setText("Clientes semanales");
        btnMenuReportes.add(jMenuItem23);

        jMenuItem24.setText("Clientes mensuales");
        btnMenuReportes.add(jMenuItem24);

        jMenuBar1.add(btnMenuReportes);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelFechaHora, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelFechaHora, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        if(!(cobrarMensualidad instanceof Cobrar)){
            cobrarMensualidad = new Cobrar();
        }
        centrarVentanaInterna(cobrarMensualidad);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        if(!(inventario instanceof Inventario)){
            inventario = new Inventario();
        }
        centrarVentanaInterna(inventario);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        if(!(ventasGenerar instanceof VentasGenerar)){
            ventasGenerar = new VentasGenerar();
        }
        centrarVentanaInterna(ventasGenerar);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void btnReintentarConexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReintentarConexionActionPerformed
        hiloConexion();
    }//GEN-LAST:event_btnReintentarConexionActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        if(!(inscripcionForm instanceof Inscripcion)){
            inscripcionForm = new Inscripcion();
        }
        centrarVentanaInterna(inscripcionForm);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        if(!(inventarioDesHab instanceof InventarioDesHab)){
            inventarioDesHab = new InventarioDesHab();
        }
        centrarVentanaInterna(inventarioDesHab);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        if(!(reporteVentas instanceof ReporteVentas)){
            reporteVentas = new ReporteVentas();
        }
        centrarVentanaInterna(reporteVentas);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        if(!(inscripcionKick instanceof InscripcionKick)){
            inscripcionKick = new InscripcionKick();
        }
        centrarVentanaInterna(inscripcionKick);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        if(!(cobrarKick instanceof CobrarKick)){
            cobrarKick = new CobrarKick();
        }
        centrarVentanaInterna(new CobrarKick());
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        if(!(mensualesAltas instanceof MensualesAltas)){
           mensualesAltas = new MensualesAltas();
        }
        centrarVentanaInterna(new MensualesAltas());
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        if(!(semanalesAltas instanceof SemanalesAltas)){
            semanalesAltas = new SemanalesAltas();
        }
        centrarVentanaInterna(new SemanalesAltas());
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        if(!(kickBoxingAltas instanceof KickBoxingAltas)){
            kickBoxingAltas = new KickBoxingAltas();
        }
        centrarVentanaInterna(new KickBoxingAltas());
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        if(!(mensualesBajas instanceof MensualesBajas)){
            mensualesBajas = new MensualesBajas();
        }
        centrarVentanaInterna(new MensualesBajas());
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        if(!(semanalesBajas instanceof SemanalesBajas)){
            semanalesBajas = new SemanalesBajas();
        }
        centrarVentanaInterna(new SemanalesBajas());
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        if(!(kickBoxingBajas instanceof KickBoxingBajas)){
            kickBoxingBajas = new KickBoxingBajas();
        }
        centrarVentanaInterna(new KickBoxingBajas());
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        if(!(reportePagos instanceof ReportePagos)){
            reportePagos = new ReportePagos();
        }
        centrarVentanaInterna(new ReportePagos());
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        if(!(reporteMensualidades instanceof ReporteMensualidades)){
            reporteMensualidades = new ReporteMensualidades();
        }
        centrarVentanaInterna(new ReporteMensualidades());
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        if(!(reportePagosSemanales instanceof ReportePagosSemanales)){
            reportePagosSemanales = new ReportePagosSemanales();
        }
        centrarVentanaInterna(new ReportePagosSemanales());
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
        if(!(reporteVisitas instanceof ReporteVisitas)){
            reporteVisitas = new ReporteVisitas();
        }
        centrarVentanaInterna(new ReporteVisitas());
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    private void jMenuItem19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem19ActionPerformed
        if(!(reportePagosKick instanceof ReportePagosKick)){
            reportePagosKick = new ReportePagosKick();
        }
        centrarVentanaInterna(new ReportePagosKick());
    }//GEN-LAST:event_jMenuItem19ActionPerformed

    private void jMenuItem20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem20ActionPerformed
        if(!(reporteInventario instanceof ReporteInventario)){
            reporteInventario = new ReporteInventario();
        }
        centrarVentanaInterna(new ReporteInventario());
    }//GEN-LAST:event_jMenuItem20ActionPerformed

    private void jMenuItem21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem21ActionPerformed
        if(!(reporteAlumnosKick instanceof ReporteAlumnosKick)){
            reporteAlumnosKick = new ReporteAlumnosKick();
        }
        centrarVentanaInterna(new ReporteAlumnosKick());
    }//GEN-LAST:event_jMenuItem21ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    UIManager.setLookAndFeel(new GraphiteLookAndFeel());
                    new Principal().setVisible(true);
                } catch (UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu btnMenuAltasBajas;
    private javax.swing.JMenu btnMenuCobros;
    private javax.swing.JMenu btnMenuInscripcion;
    private javax.swing.JMenu btnMenuInventario;
    private javax.swing.JMenu btnMenuReportes;
    private javax.swing.JMenu btnMenuVenta;
    private javax.swing.JButton btnReintentarConexion;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JLabel labelBienvenida;
    private javax.swing.JLabel labelCargando;
    private javax.swing.JLabel labelEstadoConexion;
    private javax.swing.JLabel labelFechaHora;
    // End of variables declaration//GEN-END:variables
}
